//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/GameInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputs"",
    ""maps"": [
        {
            ""name"": ""Player1"",
            ""id"": ""8b2a8529-af44-4df1-9ce7-bc490213be83"",
            ""actions"": [
                {
                    ""name"": ""OnMove"",
                    ""type"": ""Value"",
                    ""id"": ""452d5837-7cd1-4f2e-b3ad-f3820ceaf5e1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OnJump"",
                    ""type"": ""Button"",
                    ""id"": ""1a89076c-023d-41ec-8358-4ee8a1cf34c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c6bea922-93f0-4b82-ab9b-c00adc2dbc9d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d12f5dd8-933d-4b3c-aae4-58e0e6a5cae9"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player2_support"",
            ""id"": ""4b026d7f-4ae8-4015-8221-9d6f833086de"",
            ""actions"": [
                {
                    ""name"": ""putFooting"",
                    ""type"": ""Button"",
                    ""id"": ""7793e188-f4bf-4bdc-b46b-7cea8a22859b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""changeKindOfFooting"",
                    ""type"": ""Button"",
                    ""id"": ""e7c67352-d2c1-4ee4-b3b5-a7c4d0546a13"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""changeLengthOfFooting"",
                    ""type"": ""Button"",
                    ""id"": ""053ccf85-ba92-438b-947d-1889ebcffb1d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""changeKindOfWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""e7892b52-0eaf-48aa-9379-fa68d9ce2bf1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""507ff07f-9cbb-4d95-bd84-a8c9000962ca"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""putFooting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e48d8d95-2e49-4e52-989c-6daa57c99237"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""changeKindOfFooting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41bbf51c-3e08-443d-be95-ad78fb306450"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""changeLengthOfFooting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3a9bed4-be5f-491a-8547-a12efd2083b2"",
                    ""path"": ""<Keyboard>/leftMeta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""changeKindOfWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""356f9c2c-be11-4a04-8692-f2a8c07ba6c1"",
                    ""path"": ""<Keyboard>/rightMeta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""changeKindOfWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player1
        m_Player1 = asset.FindActionMap("Player1", throwIfNotFound: true);
        m_Player1_OnMove = m_Player1.FindAction("OnMove", throwIfNotFound: true);
        m_Player1_OnJump = m_Player1.FindAction("OnJump", throwIfNotFound: true);
        // Player2_support
        m_Player2_support = asset.FindActionMap("Player2_support", throwIfNotFound: true);
        m_Player2_support_putFooting = m_Player2_support.FindAction("putFooting", throwIfNotFound: true);
        m_Player2_support_changeKindOfFooting = m_Player2_support.FindAction("changeKindOfFooting", throwIfNotFound: true);
        m_Player2_support_changeLengthOfFooting = m_Player2_support.FindAction("changeLengthOfFooting", throwIfNotFound: true);
        m_Player2_support_changeKindOfWeapon = m_Player2_support.FindAction("changeKindOfWeapon", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player1
    private readonly InputActionMap m_Player1;
    private List<IPlayer1Actions> m_Player1ActionsCallbackInterfaces = new List<IPlayer1Actions>();
    private readonly InputAction m_Player1_OnMove;
    private readonly InputAction m_Player1_OnJump;
    public struct Player1Actions
    {
        private @GameInputs m_Wrapper;
        public Player1Actions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @OnMove => m_Wrapper.m_Player1_OnMove;
        public InputAction @OnJump => m_Wrapper.m_Player1_OnJump;
        public InputActionMap Get() { return m_Wrapper.m_Player1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player1Actions set) { return set.Get(); }
        public void AddCallbacks(IPlayer1Actions instance)
        {
            if (instance == null || m_Wrapper.m_Player1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player1ActionsCallbackInterfaces.Add(instance);
            @OnMove.started += instance.OnOnMove;
            @OnMove.performed += instance.OnOnMove;
            @OnMove.canceled += instance.OnOnMove;
            @OnJump.started += instance.OnOnJump;
            @OnJump.performed += instance.OnOnJump;
            @OnJump.canceled += instance.OnOnJump;
        }

        private void UnregisterCallbacks(IPlayer1Actions instance)
        {
            @OnMove.started -= instance.OnOnMove;
            @OnMove.performed -= instance.OnOnMove;
            @OnMove.canceled -= instance.OnOnMove;
            @OnJump.started -= instance.OnOnJump;
            @OnJump.performed -= instance.OnOnJump;
            @OnJump.canceled -= instance.OnOnJump;
        }

        public void RemoveCallbacks(IPlayer1Actions instance)
        {
            if (m_Wrapper.m_Player1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayer1Actions instance)
        {
            foreach (var item in m_Wrapper.m_Player1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Player1Actions @Player1 => new Player1Actions(this);

    // Player2_support
    private readonly InputActionMap m_Player2_support;
    private List<IPlayer2_supportActions> m_Player2_supportActionsCallbackInterfaces = new List<IPlayer2_supportActions>();
    private readonly InputAction m_Player2_support_putFooting;
    private readonly InputAction m_Player2_support_changeKindOfFooting;
    private readonly InputAction m_Player2_support_changeLengthOfFooting;
    private readonly InputAction m_Player2_support_changeKindOfWeapon;
    public struct Player2_supportActions
    {
        private @GameInputs m_Wrapper;
        public Player2_supportActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @putFooting => m_Wrapper.m_Player2_support_putFooting;
        public InputAction @changeKindOfFooting => m_Wrapper.m_Player2_support_changeKindOfFooting;
        public InputAction @changeLengthOfFooting => m_Wrapper.m_Player2_support_changeLengthOfFooting;
        public InputAction @changeKindOfWeapon => m_Wrapper.m_Player2_support_changeKindOfWeapon;
        public InputActionMap Get() { return m_Wrapper.m_Player2_support; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player2_supportActions set) { return set.Get(); }
        public void AddCallbacks(IPlayer2_supportActions instance)
        {
            if (instance == null || m_Wrapper.m_Player2_supportActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player2_supportActionsCallbackInterfaces.Add(instance);
            @putFooting.started += instance.OnPutFooting;
            @putFooting.performed += instance.OnPutFooting;
            @putFooting.canceled += instance.OnPutFooting;
            @changeKindOfFooting.started += instance.OnChangeKindOfFooting;
            @changeKindOfFooting.performed += instance.OnChangeKindOfFooting;
            @changeKindOfFooting.canceled += instance.OnChangeKindOfFooting;
            @changeLengthOfFooting.started += instance.OnChangeLengthOfFooting;
            @changeLengthOfFooting.performed += instance.OnChangeLengthOfFooting;
            @changeLengthOfFooting.canceled += instance.OnChangeLengthOfFooting;
            @changeKindOfWeapon.started += instance.OnChangeKindOfWeapon;
            @changeKindOfWeapon.performed += instance.OnChangeKindOfWeapon;
            @changeKindOfWeapon.canceled += instance.OnChangeKindOfWeapon;
        }

        private void UnregisterCallbacks(IPlayer2_supportActions instance)
        {
            @putFooting.started -= instance.OnPutFooting;
            @putFooting.performed -= instance.OnPutFooting;
            @putFooting.canceled -= instance.OnPutFooting;
            @changeKindOfFooting.started -= instance.OnChangeKindOfFooting;
            @changeKindOfFooting.performed -= instance.OnChangeKindOfFooting;
            @changeKindOfFooting.canceled -= instance.OnChangeKindOfFooting;
            @changeLengthOfFooting.started -= instance.OnChangeLengthOfFooting;
            @changeLengthOfFooting.performed -= instance.OnChangeLengthOfFooting;
            @changeLengthOfFooting.canceled -= instance.OnChangeLengthOfFooting;
            @changeKindOfWeapon.started -= instance.OnChangeKindOfWeapon;
            @changeKindOfWeapon.performed -= instance.OnChangeKindOfWeapon;
            @changeKindOfWeapon.canceled -= instance.OnChangeKindOfWeapon;
        }

        public void RemoveCallbacks(IPlayer2_supportActions instance)
        {
            if (m_Wrapper.m_Player2_supportActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayer2_supportActions instance)
        {
            foreach (var item in m_Wrapper.m_Player2_supportActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player2_supportActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Player2_supportActions @Player2_support => new Player2_supportActions(this);
    public interface IPlayer1Actions
    {
        void OnOnMove(InputAction.CallbackContext context);
        void OnOnJump(InputAction.CallbackContext context);
    }
    public interface IPlayer2_supportActions
    {
        void OnPutFooting(InputAction.CallbackContext context);
        void OnChangeKindOfFooting(InputAction.CallbackContext context);
        void OnChangeLengthOfFooting(InputAction.CallbackContext context);
        void OnChangeKindOfWeapon(InputAction.CallbackContext context);
    }
}
